USE CASPER;

CREATE OR REPLACE VIEW PROF_VIEW AS 
       SELECT DISTINCT(Instructor) FROM TEMP;

INSERT INTO PROF (Name) 
SELECT Instructor FROM PROF_VIEW WHERE 
(Instructor NOT IN (SELECT Name FROM PROF));
